import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Navbar } from "@/components/Navbar";
import { CustomCursor } from "@/components/CustomCursor";
import { NoiseOverlay } from "@/components/NoiseOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-transparent text-slate-900 dark:text-gray-100 transition-colors duration-500 overflow-x-hidden selection:bg-fuchsia-500/30">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false}>
          <NoiseOverlay />
          {/* Clean Vercel-style Background */}
          <div className="fixed inset-0 pointer-events-none -z-50 bg-white dark:bg-[#0a0a0a] transition-colors duration-500">
            {/* Subtle noise texture */}
            <div 
              className="absolute inset-0 opacity-[0.03] dark:opacity-[0.02] mix-blend-overlay" 
              style={{ 
                backgroundImage: "url('data:image/svg+xml,%3Csvg viewBox=%220 0 200 200%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter id=%22noiseFilter%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.65%22 numOctaves=%223%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23noiseFilter)%22/%3E%3C/svg%3E')" 
              }} 
            />
            {/* Extremely subtle top glow to prevent pitch black flatness */}
            <div className="absolute top-0 left-0 right-0 h-[500px] bg-gradient-to-b from-slate-200/20 to-transparent dark:from-white/[0.02] dark:to-transparent pointer-events-none" />
          </div>

          <CustomCursor />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
